# Site wide configuration

title: Funky Penguin
locale: en_US
description: Upgrading the world through the skilled application of technology
logo: site-logo.png
search: true
url: https://www.funkypenguin.co.nz

# No reason not to publish future-dated posts.
future: true

# Jekyll configuration

permalink:   /:categories/:title/
markdown:    kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-paginate
  - jemoji
  - jekyll-seo-tag
  - jekyll-redirect-from
  - jekyll-mentions
  - jekyll-crosspost-to-medium

paginate: 7
paginate_path: "/blog/page:num/"

# Add me some recipies
collections:
  recipies:
    output: true
    permalink: /:collection/:path/
    title: FAQs

kramdown:
  input: GFM
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..2
  enable_coderay: false

mathjax: true

discourse_url: "https://discourse.geek-kitchen.funkypenguin.co.nz"

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", ".less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md", "vendor"]


# Site owner
owner:
  name: David Young
  avatar: bio-photo.jpg
  email: davidy@funkypenguin.co.nz
  disqus-shortname:
  twitter: funkypenguin
  facebook: #username
  github: funkypenguin
  stackexchange: #http://stackoverflow.com/users/123456/username
  linkedin: funkypenguin
  mastodon: https://mastodon.funkypenguin.co.nz
  instagram: #username
  flickr: #username
  tumblr: #username
  pinterest: #username
  weibo: #userid
  google:
    plus: #username
    analytics: UA-139253-8
    verify:
    ad-client:
    ad-slot:
  bing-verify:

# Yes, I want social sharing on every page:
share: true

# Required for the jekyll-seo-tag gem
# Social Sharing
twitter:
  username               : funkypenguin
og_image                 : # Open Graph/Twitter default site image
# For specifying social profiles
# - https://developers.google.com/structured-data/customize/social-profiles
social:
  links: # An array of links to social media profiles
    - https://twitter.com/funkypenguin
    - https://github.com/funkypenguin
    - https://keybase.io/funkypenguin
    - https://plus.google.com/u/0/+DavidYoungFunkyPenguin
