# This file exists for local dev, where I want to force the URL, and
# Disable the crosspost-to-medium plugin (by redefining the active plugins)
url: http://localhost:4000
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate
  - jemoji
  - jekyll-redirect-from
